// <auto-generated />
using AppiMinistros.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppiMinistros.Migrations
{
    [DbContext(typeof(Oferente_DbContext))]
    [Migration("20240327110342_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppiMinistros.Models.Experiencia_trabajo", b =>
                {
                    b.Property<int>("Idtrabajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idtrabajo"));

                    b.Property<int>("Anio_fin")
                        .HasColumnType("int");

                    b.Property<int>("Anio_inicio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Empresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OferenteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Idtrabajo");

                    b.HasIndex("OferenteId");

                    b.ToTable("TbExpLaboral");
                });

            modelBuilder.Entity("AppiMinistros.Models.Oferente", b =>
                {
                    b.Property<string>("OferenteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FechaNacimiento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OferenteId");

                    b.ToTable("TbOferente");
                });

            modelBuilder.Entity("AppiMinistros.Models.Titulo", b =>
                {
                    b.Property<int>("TituloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TituloId"));

                    b.Property<int>("Anio_titulo")
                        .HasColumnType("int");

                    b.Property<string>("CentroUniversitario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("GradoAcademico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OferenteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TituloId");

                    b.HasIndex("OferenteId");

                    b.ToTable("Tbtitulos");
                });

            modelBuilder.Entity("AppiMinistros.Models.Experiencia_trabajo", b =>
                {
                    b.HasOne("AppiMinistros.Models.Oferente", null)
                        .WithMany("list_Experiencia_laboral")
                        .HasForeignKey("OferenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppiMinistros.Models.Titulo", b =>
                {
                    b.HasOne("AppiMinistros.Models.Oferente", null)
                        .WithMany("titulos")
                        .HasForeignKey("OferenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppiMinistros.Models.Oferente", b =>
                {
                    b.Navigation("list_Experiencia_laboral");

                    b.Navigation("titulos");
                });
#pragma warning restore 612, 618
        }
    }
}
